
export const indianCities = [
    "Achalpur", "Adilabad", "Adityapur", "Adoni", "Agartala", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer",
    "Akola", "Alandur", "Alappuzha", "Aligarh", "Allahabad", "Alwar", "Ambala", "Ambala Sadar", "Ambarnath", "Ambattur",
    "Ambikapur", "Ambur", "Amravati", "Amreli", "Amritsar", "Amroha", "Anand", "Anantapur", "Anantnag", "Arrah",
    "Asansol", "Ashoknagar Kalyangarh", "Aurangabad", "Avadi", "Azamgarh", "Badlapur", "Bagaha", "Bagalkot", "Bahadurgarh", "Baharampur",
    "Bahraich", "Baidyabati", "Balaghat", "Balasore", "Ballia", "Bally", "Balurghat", "Banda", "Bankura", "Bansberia",
    "Banswara", "Baran", "Barasat", "Baraut", "Bardhaman", "Bareilly", "Baripada", "Barnala", "Barrackzore", "Barwani",
    "Basirhat", "Basti", "Batala", "Bathinda", "Beawar", "Begusarai", "Belgaum", "Bellary", "Bengaluru", "Bettiah",
    "Betul", "Bhadrak", "Bhadravati", "Bhadreswar", "Bhagalpur", "Bhalswa Jahangir Pur", "Bharatpur", "Bharuch", "Bhatpara", "Bhavnagar",
    "Bhilai", "Bhilwara", "Bhimavaram", "Bhind", "Bhiwadi", "Bhiwandi", "Bhiwani", "Bhopal", "Bhubaneswar", "Bhuj",
    "Bhusawal", "Bidar", "Bidhannagar", "Bihar Sharif", "Bijapur", "Bikaner", "Bilaspur", "B Bokaro Steel City", "Bongaon", "Botad",
    "Budaun", "Bulandshahr", "Bundi", "Burhanpur", "Buxar", "Champdani", "Chandigarh", "Chandrapur", "Chapra", "Chas",
    "Chennai", "Chhatarpur", "Chhindwara", "Chikmagalur", "Chittoor", "Chittorgarh", "Churu", "Coimbatore", "Cuttack", "Dabagram",
    "Dallo Pura", "Damoh", "Darbhanga", "Darjeeling", "Datia", "Davanagere", "Dehradun", "Dehri", "Delhi", "Deoghar",
    "Deoria", "Dewas", "Dhanbad", "Dharmavaram", "Dholpur", "Dhule", "Dibrugarh", "Dimapur", "Dinapur Nizamat", "Dindigul",
    "Durg", "Durgapur", "Eluru", "English Bazar", "Erode", "Etawah", "Faridabad", "Faridkot", "Farrukhabad", "Fatehpur",
    "Firozabad", "Firozpur", "Gadag-Betigeri", "Gandhidham", "Gandhinagar", "Ganganagar", "Gangapur", "Gangawati", "Gaya", "Ghaziabad",
    "Ghazipur", "Giridih", "Godhra", "Gonda", "Gondia", "Gorakhpur", "Greater Noida", "Gudivada", "Gulbarga", "Guna",
    "Guntakal", "Guntur", "Gurgaon", "Guwahati", "Gwalior", "Habra", "Hajipur", "H Haldia", "Haldwani-cum-Kathgodam", "Halisahar",
    "Hanumangarh", "Hapur", "Hardoi", "Hardwar", "Hassan", "Hathras", "Hazaribag", "Hindupur", "Hinganghat", "Hisar",
    "Hoshangabad", "Hoshiarpur", "Hospet", "Howrah", "Hubli-Dharwad", "Hugli-Chinsurah", "Hyderabad", "Ichalkaranji", "Imphal", "Indore",
    "Itarsi", "Jabalpur", "Jagdalpur", "Jagadhri", "Jaipur", "Jalandhar", "Jalgaon", "Jalna", "Jalpaiguri", "Jamalpur",
    "Jammu", "Jamnagar", "Jamshedpur", "Jaunpur", "Jehanabad", "Jetpur", "Jhansi", "Jharsuguda", "Jhunjhunu", "Jind",
    "Jodhpur", "Jorhat", "Junagadh", "Kadapa", "Kakinada", "Kalol", "Kalyan-Dombivli", "Kamarhati", "Kancheepuram", "Kanchrapara",
    "Kanpur", "Kanyakumari", "Kapurthala", "Karaikkudi", "Karawal Nagar", "Karimnagar", "Karnal", "Kasganj", "Kashipur", "Katihar",
    "Katni", "Kavali", "Khammam", "Khandwa", "Kharagpur", "Khardaha", "Khargone", "Khora", "Kishanganj", "Kishangarh",
    "Kochi", "Kohima", "Kolar", "Kolhapur", "Kolkata", "Kollam", "Korba", "Kota", "Kottayam", "Kozhikode",
    "Krishnanagar", "Kuchaman City", "Kumbakonam", "Kurnool", "Lakhimpur", "Lalitpur", "Latur", "Loni", "Lucknow", "Ludhiana",
    "Machilipatnam", "Madanapalle", "Madhyamgram", "Madurai", "Mahbubnagar", "Maheshtala", "Mainpuri", "Malegaon", "Malerkotla", "Malda",
    "Mandya", "Mangalore", "Mango", "Mathura", "Maunath Bhanjan", "Medinipur", "Meerut", "Mehsana", "Mira-Bhayandar", "Mirzapur",
    "Moga", "Mohali", "Moradabad", "Morena", "Morbi", "Motihari", "Mumbai", "Munger", "Murwara", "Muzaffarnagar",
    "Muzaffarpur", "Mysore", "Nabadwip", "Nadiad", "Nagaon", "Nagapattinam", "Nagaur", "Nagda", "Nagercoil", "Nagpur",
    "Naihati", "Nanded", "Nandyal", "Nangloi Jat", "Narasaraopet", "Nashik", "Navi Mumbai", "Navsari", "Neemuch", "Nellore",
    "New Delhi", "Neyveli", "Nizamabad", "Noida", "North Barrackpur", "North Dumdum", "Ongole", "Orai", "Osmanabad", "Ozhukarai",
    "Palakkad", "Palanpur", "Pali", "Pallavaram", "Palwal", "Panchkula", "Panihati", "Panipat", "Panvel", "Parbhani",
    "Patan", "Pathankot", "Patiala", "Patna", "Phagwara", "Phusro", "Pilibhit", "Pimpri-Chinchwad", "Pithampur", "Pollachi",
    "Pondicherry", "Porbandar", "Port Blair", "Proddatur", "Pudukkottai", "Pune", "Puri", "Purnia", "Purulia", "Raebareli",
    "Raichur", "Raiganj", "Raigarh", "Raipur", "Rajahmundry", "Rajapalayam", "Rajarhat Gopalpur", "Rajkot", "Rajinandgaon", "Rajpur Sonarpur",
    "Ramagundam", "Rampur", "Ranchi", "Ranibennur", "Raniganj", "Ratlam", "Ratnagiri", "Raurkela", "Rewa", "Rewari",
    "Rishra", "Robertson Pet", "Rohtak", "Roorkee", "Rudrapur", "Sagar", "Saharanpur", "Saharsa", "Salem", "Sambalpur",
    "Sambhal", "Sangli-Miraj & Kupwad", "Sangrur", "Santipur", "Sasaram", "Satara", "Satna", "Sawai Madhopur", "Secunderabad", "Sehore",
    "Seoni", "Serampore", "Shahjahanpur", "Shamli", "Shikohabad", "Shillong", "Shimla", "Shimoga", "Shivpuri", "Sikar",
    "Silchar", "Siliguri", "Singrauli", "Sirsa", "Sitamarhi", "Sitapur", "Sivakasi", "Siwan", "Solapur", "Sonipat",
    "South Dumdum", "Srikakulam", "Srinagar", "Sujangarh", "Sultan Pur Majra", "Sultanpur", "Surat", "Surendranagar Dudhrej", "Suri", "Suryapet",
    "Tadepalligudem", "Tadipatri", "Tambaram", "Tenali", "Tezpur", "Thane", "Thanesar", "Thanjavur", "Thiruvananthapuram", "Thoothukudi",
    "Thrissur", "Tiruchirappalli", "Tirunelveli", "Tirupati", "Tiruppur", "Tiruvannamalai", "Tiruvottiyur", "Titagarh", "Tonk", "Tumkur",
    "Udaipur", "Udgir", "Udupi", "Ujjain", "Ulhasnagar", "Uluberia", "Unnao", "Vadodara", "Valsad", "Varanasi",
    "Vasai-Virar", "Vellore", "Veraval", "Vidisha", "Vijayawada", "Visakhapatnam", "Vizianagaram", "Warangal", "Wardha", "Yamunanagar",
    "Yavatmal"
].sort();
